# Generated by Django 6.0.5 on 2026-05-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatDeteksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=255)),
                ('status_daun', models.CharField(max_length=100)),
                ('klorofil_persen', models.FloatField()),
                ('klorosis_persen', models.FloatField()),
                ('tanggal_uji', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
