# Generated by Django 6.0.5 on 2026-05-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatdeteksi',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
