# Generated by Django 6.0.5 on 2026-05-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_riwayatdeteksi_catatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatdeteksi',
            name='kerusakan_persen',
            field=models.FloatField(default=0.0),
        ),
    ]
