# Generated by Django 6.0.5 on 2026-05-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_riwayatdeteksi_kerusakan_persen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('label', models.CharField(blank=True, choices=[('Nitrogen', 'Nitrogen (N)'), ('Phosphorus', 'Phosphorus (P)'), ('Potassium', 'Potassium (K)')], max_length=50)),
                ('hasil', models.CharField(blank=True, max_length=100)),
                ('kondisi', models.CharField(blank=True, max_length=100)),
                ('green_percent', models.FloatField(default=0)),
                ('yellow_percent', models.FloatField(default=0)),
                ('brown_percent', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RiwayatDeteksi',
        ),
    ]
