# Generated by Django 6.0.5 on 2026-05-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_diagnostik_delete_riwayatdeteksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetDaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dataset/')),
                ('label', models.CharField(choices=[('Nitrogen', 'Nitrogen (N)'), ('Phosphorus', 'Phosphorus (P)'), ('Potassium', 'Potassium (K)')], max_length=50)),
                ('hasil', models.CharField(blank=True, max_length=100)),
                ('kondisi', models.CharField(blank=True, max_length=100)),
                ('green_percent', models.FloatField(default=0)),
                ('yellow_percent', models.FloatField(default=0)),
                ('brown_percent', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Diagnostik',
        ),
    ]
