# Generated by Django 6.0.5 on 2026-05-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_datasetdaun_delete_diagnostik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetdaun',
            old_name='accuracy',
            new_name='purple_percent',
        ),
        migrations.AlterField(
            model_name='datasetdaun',
            name='hasil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datasetdaun',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datasetdaun',
            name='kondisi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datasetdaun',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
