# Generated by Django 6.0.5 on 2026-05-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_rename_accuracy_datasetdaun_purple_percent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetdaun',
            old_name='purple_percent',
            new_name='accuracy',
        ),
        migrations.AlterField(
            model_name='datasetdaun',
            name='hasil',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datasetdaun',
            name='image',
            field=models.ImageField(upload_to='dataset/'),
        ),
        migrations.AlterField(
            model_name='datasetdaun',
            name='kondisi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datasetdaun',
            name='label',
            field=models.CharField(choices=[('Nitrogen', 'Nitrogen (N)'), ('Phosphorus', 'Phosphorus (P)'), ('Potassium', 'Potassium (K)')], max_length=50),
        ),
    ]
