# Generated by Django 6.0.5 on 2026-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_rename_purple_percent_datasetdaun_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdaun',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
